Proyect/Controllers/ComprarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Proyect.Models;
using Proyect.Models.AccountViewModels;
using Proyect.Services;
using Proyect;
using Proyect.Controllers;
using System.Net.Http;
using System.Net.Http.Headers;
using Proyect.Data;
using System.Runtime.Serialization.Json;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using WebApiClient;
namespace Proyect.Controllers
{
    [Authorize]
    public class ComprarController : Controller
    {
          private UserManager<ApplicationUser> _userManager { get; }
        private readonly ApplicationDbContext _context;

        public ComprarController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {

            _userManager = userManager;

            _context = context;



        }
        
           public async Task<IActionResult> Index(ProyectViewModel dato,string opcion)
        {         
            var user = await _userManager.GetUserAsync(User);
            if(user.Id!=null){
                HomeController.activado=true;
            }
            else{
                HomeController.activado=false;
            }
             foreach(var mi in _context.Users){
                 if(mi.Id==user.Id){
                     float mu=(float)mi.Efectivo;
                        HomeController.dinero=mu;
                 }
                }
            var y=WebApiClient.Program.ProcessRepositories(opcion).Result;
            if(y.items==null){
                ViewBag.error=true;
            }
            else{
                ViewBag.error=false;
            }
            ViewBag.lista=y;
            var d =y;
          return View();
        }
        public async Task<IActionResult> Opcion(){
            var user = await _userManager.GetUserAsync(User);
             if(user.Id!=null){
                HomeController.activado=true;
            }
            else{
                HomeController.activado=false;
            }
             foreach(var mi in _context.Users){
                 if(mi.Id==user.Id){
                     float mu=(float)mi.Efectivo;
                        HomeController.dinero=mu;
                 }
                }
            return View();
        }
         public async Task<IActionResult>  Comprado(Ropa m)
        {
            var user = await _userManager.GetUserAsync(User);
             if(user.Id!=null){
                HomeController.activado=true;
            }
            else{
                HomeController.activado=false;
            }
            m.OwnerId = new Guid(user.Id);
            _context.Prenda.Add(m);
            _context.SaveChanges();
            foreach(var d in _context.Users){
                if(d.Id==m.OwnerId.ToString()){
                    if(d.Efectivo-m.precio>0){
                        float x=(float)m.precio;
                        d.Efectivo=d.Efectivo-x;
                        float y=(float)d.Efectivo;
                        HomeController.dinero=y;
                        _context.SaveChanges();
                        ViewBag.comprar=true;
                        ViewBag.lista=_context.Prenda;
                    }
                    else{
                        ViewBag.comprar=false;
                    }
                }
            }
            ViewBag.identidad=new Guid(user.Id);
            
            return View();
            
        }
        public async Task<IActionResult>  MisCompras(){
             var user = await _userManager.GetUserAsync(User);
              if(user.Id!=null){
                HomeController.activado=true;
            }
            else{
                HomeController.activado=false;
            }
             ViewBag.lista=_context.Prenda;
             ViewBag.identidad=new Guid(user.Id);
             return View();
        }


    }

}

Proyect/Controllers/TarjetaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Proyect.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Proyect.Data;
namespace Proyect.Controllers

{
    [Authorize]
    public class TarjetaController : Controller

    {
        private UserManager<ApplicationUser> _userManager { get; }
        /// Aquí usamamos DI para obtener el DbContext
        private readonly ApplicationDbContext _context;
        /// Aquí usamamos DI para obtener el DbContext
        public TarjetaController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;

            _context = context;
        }

        public IActionResult Index()

        {

            return View();

        }



        public async Task<IActionResult>  Validar(string tarjetanum,string cantidad)

        {
            double dato=Convert.ToDouble(cantidad);
            float valor=(float)dato;
             Tarjeta tarjeta = new Tarjeta(tarjetanum);
            var user = await _userManager.GetUserAsync(User);
             if(user.Id!=null){
                HomeController.activado=true;
            }
            else{
                HomeController.activado=false;
            }
             foreach(var mi in _context.Users){
                 if(mi.Id==user.Id){
                     if(tarjeta.Valida==true){
                         mi.Efectivo=mi.Efectivo+valor;
                         float valores=(float)mi.Efectivo;
                         HomeController.dinero=valores;
                         _context.SaveChanges();
                         ViewBag.agregado=true;
                         break;
                     }
                     else{
                         ViewBag.agregado=false;
                     }
                 }
                }

           
            
            return View();

        }





        public IActionResult Error()

        {

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });

        }

    }

}

Proyect/Views/Comprar/Comprado.cshtml
@model Dato
@{

    ViewData["Title"] = "Comprado";

}
<div>
    @if(ViewBag.comprar==true){
         <table class="table table-hover">
      <thead>
          <tr>
              <td><b>Nombre</b></td>
              <td><b>Marca</b></td>
              <td><b>Precio</b></td>
              <td><b>Id del Producto:</b></td>
              <td><b>Tamaño:</b></td>
              <td><b>Comprada:</b></td>
              <td><b>Imagen</b></td>
          </tr>
      </thead>
    @foreach(var items in ViewBag.lista){
        @if(ViewBag.identidad==items.OwnerId){
        <tr>
            
            <td>@items.Nombre</td>
            <td>@items.Marca</td>
            <td>@items.precio</td>
             <td>@items.id_del_producto</td>
             <td>@items.Tamano</td>
             <td>@items.Comprada</td>
             <td><img src="@items.imagen" /> </td>
             
        </tr>
        }
    }
    </table>
    }
    else{
        <img  src="~/images/sin_dinero.png" alt="#">
         <form asp-action="Opcion" asp-controller="Comprar" method="post" >
         <button style="background-color:crimson; width:200px; color:white;" class="btn btn-lg btn-primary btn-block" type="submit">Regresar</button>
         </form>
         <form style="background-color:crimson; width:200px; color:white;" asp-action="Index" asp-controller="Tarjeta" method="post" >
         <button class="btn btn-lg btn-primary btn-block" type="submit">Obtener Dinero</button>
         </form>
    }
</div>

Proyect/Views/Comprar/Index.cshtml
@model Ropa
@{
    var d=ViewBag.lista;
    var error=ViewBag.error;
}
@{

    ViewData["Title"] = "Catalogo";

}
<div>
    @if(error==false){
    <font size=8 color="red"><center>Items</center></font>
    @foreach(var y in d.items){
    <form asp-action="Comprado" asp-controller="Comprar">
    <div style="size:60px" ><img style="float: left; " src="@y.mediumImage" />  
    <font color="green" size=5 ><b>Id del producto:  </b></font><font size=4> @y.itemId </font>
    <br/>
    <font color="green" size=5>Precio: </font><font size=4> @y.salePrice </font>
    <br/>
    <font color="teal" size=5>Nombre: </font><font size=4> @y.name </font> <font color="teal" size=5>   Categoria:  </font><font size=4>  @y.categoryPath</font>
    <br/>
    <font color="green" size=5>Genero: </font><font size=4> @y.gender</font>
    <br/>
    <font color="blue" size=5>Descripcion:  </font><font size=4><b> @y.shortDescription </b></font>
    <font color="blue" size=5>Marca:   </font><font size=4> @y.brandName    </font>
    <font color="blue" size=5>Tamaño: </font><font size=4> @y.size  </font> <font size=5 color="blue">  Color:  @y.color </font>
    <input type="hidden" id="Nombre" name="Nombre" value="@y.name">
    <input type="hidden" id="Marca" name="Marca" value="@y.brandName">
    <input type="hidden" id="precio" name="precio" value="@y.salePrice">
    <input type="hidden" id="id_del_producto" name="id_del_producto" value="@y.itemId">
    <input type="hidden" id="Tamano" name="Tamano" value="@y.size">
    <input type="hidden" id="imagen" name="imagen" value="@y.thumbnailImage">
    <br/>
    <button style="background-color:darkgreen; width:200px; color:white;" class="btn btn-danger" type="submit">Comprar</button>
    <br style="clear: left;"/>
    </div>
    </form>
}}
else{
    
<img  src="~/images/pagina_no_encontrada.jpg" alt="#">
}
</div>

Proyect/Views/Comprar/MisCompras.cshtml
@model Dato
 @{

    ViewData["Title"] = "Mis Compras";

}
<div>
         <table class="table table-hover">
      <thead>
          <tr>
              <td><b>Nombre</b></td>
              <td><b>Marca</b></td>
              <td><b>Precio</b></td>
              <td><b>Id del Producto:</b></td>
              <td><b>Tamaño:</b></td>
              <td><b>Comprada:</b></td>
              <td><b>Imagen</b></td>
          </tr>
      </thead>
    @foreach(var items in ViewBag.lista){
        @if(ViewBag.identidad==items.OwnerId){
        <tr>
            
            <td>@items.Nombre</td>
            <td>@items.Marca</td>
            <td>@items.precio</td>
             <td>@items.id_del_producto</td>
             <td>@items.Tamano</td>
             <td>@items.Comprada</td>
             <td><img src="@items.imagen" /> </td>
             
        </tr>
        }
    }
    </table>
</div>